services:
  download:
    user: root
    build: .
    entrypoint: ["python3", "/app/scripts/data_acquisition/download_kaggle.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true

  etl:
    user: root
    build: .
    entrypoint: ["python3", "/app/scripts/data_acquisition/etl.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true

  preprocess:
    user: root
    build: .
    entrypoint:
      ["python3", "/app/src/Pneumonia_Detection/preprocessing/main.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true

  visualization:
    user: root
    build: .
    entrypoint:
      ["python3", "/app/src/Pneumonia_Detection/visualization/main.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
      - ./images:/app/images
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
      - OUTPUTS_PATH=/app/images
      - MAX_ROWS=3000 # Número máximo de filas a procesar por lote. Ajusta este valor según la memoria disponible del contenedor o del equipo host.
    tty: true

  training_prep:
    user: root
    build: .
    entrypoint: ["python3", "/scripts/training/prepare.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true

  modeling_baseline:
    user: root
    build: .
    entrypoint: ["python3", "/scripts/training/train_baseline.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true

  modeling_cnn:
    user: root
    build: .
    entrypoint: ["python3", "/scripts/training/train_cnn.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true
