services:
  etl:
    build: .
    user: root
    image: pneumonia-etl:latest
    entrypoint: ["python3", "/app/scripts/data_acquisition/etl.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
    tty: true

  download:
    image: pneumonia-etl:latest
    build: .
    user: root
    entrypoint: ["python3", "/app/scripts/data_acquisition/download_kaggle.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database

  preprocess:
    image: pneumonia-etl:latest
    build: .
    user: root
    entrypoint: ["python3", "/app/src/Pneumonia_Detection/preprocessing/main.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database

  visualization:
    image: pneumonia-etl:latest
    build: .
    user: root
    entrypoint: ["python3", "/app/src/Pneumonia_Detection/visualization/main.py"]
    volumes:
      - ./src/Pneumonia_Detection/database:/app/src/Pneumonia_Detection/database
      . ./images:/app/images
    environment:
      - BASE_ETL_PATH=/app/src/Pneumonia_Detection/database
      - OUTPUTS_PATH=/app/images